#!/usr/bin/env bash
# Local, no-cluster regression tests for scripts/render-gitops-applications.sh —
# GO-1 Gate 1's chosen root/child Argo Application generation mechanism (multi-
# source Application, both root and child env-values sources pinned to the exact
# same --env-revision SHA). Builds an isolated SCRATCH git repository so these tests
# never touch or require a commit in the actual project repository.
#
# Closes DEF-005 (multi-source values lookup was broken: basename-only
# `$values/values.yaml` reference plus a `path` on the values-only source that
# also enabled unintended resource generation) and DEF-006 (rendering two
# separately-parameterized Applications did not prove the root's own source
# produces the child; the release/image validation duplicated
# render-gitops-release.sh's logic instead of reusing it, and so never actually
# caught an image mismatch).

set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
render="$repo_root/scripts/render-gitops-applications.sh"

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

fail_count=0
assert() {
  local desc="$1" cond="$2"
  if [[ "$cond" -eq 0 ]]; then
    printf 'PASS: %s\n' "$desc"
  else
    printf 'FAIL: %s\n' "$desc"
    fail_count=$((fail_count + 1))
  fi
}

# --- Build a minimal scratch repo: one commit with a chart, then a commit adding ---
# --- env content (release record + values + a root pointer file at apps/dev/) at ---
# --- revision A, then ANOTHER commit later (revision B) simulating "the branch/ ---
# --- HEAD moved forward" after revision A was already reviewed/approved/pinned. ---
scratch="$work/scratch-repo"
mkdir -p "$scratch/charts/bedoux/templates" "$scratch/env" "$scratch/apps/dev"
cat >"$scratch/charts/bedoux/Chart.yaml" <<'EOF'
apiVersion: v2
name: bedoux
version: 0.1.0
EOF
git -C "$scratch" init -q
git -C "$scratch" config user.email test@example.invalid
git -C "$scratch" config user.name "GO-1 test"
git -C "$scratch" add -A
git -C "$scratch" commit -q -m "scratch chart"
pinned_app_sha=$(git -C "$scratch" rev-parse HEAD)

api_digest="sha256:$(python3 -c "import hashlib;print(hashlib.sha256(b'apps-api').hexdigest())")"
web_digest="sha256:$(python3 -c "import hashlib;print(hashlib.sha256(b'apps-web').hexdigest())")"

write_release_content() {
  local release_id="$1"
  cat <<EOF
environment: dev
appRevision: "$pinned_app_sha"
chart:
  path: charts/bedoux
releaseId: "$release_id"
images:
  api: "example.invalid/bedoux-api@${api_digest}"
  web: "example.invalid/bedoux-web@${web_digest}"
EOF
}
write_values_content() {
  cat <<EOF
pairedAppRevision: "$pinned_app_sha"
api:
  image:
    repository: example.invalid/bedoux-api
    digest: "${api_digest}"
web:
  image:
    repository: example.invalid/bedoux-web
    digest: "${web_digest}"
EOF
}

write_release_content "dev-0001" >"$scratch/env/release-record.yaml"
write_values_content >"$scratch/env/values.yaml"
cat >"$scratch/apps/dev/dev-child.yaml" <<'EOF'
childAppName: dev-child
releaseRecordPath: env/release-record.yaml
valuesPath: env/values.yaml
EOF
git -C "$scratch" add -A
git -C "$scratch" commit -q -m "revision A: dev-0001 release content + root pointer"
revision_a=$(git -C "$scratch" rev-parse HEAD)

# Simulate "HEAD moved forward" — a LATER commit changes the release record to a
# different releaseId, exactly modeling a subsequent promotion PR merging after
# revision A was already reviewed and pinned by some caller. The root pointer file
# itself never changes and never declares its own commit SHA — advancing the
# pinned --env-revision is the ONLY thing that "advances the root" (DEF-006 close
# criterion: "how a reviewed promotion advances the root without requiring a
# static file to contain its own commit SHA").
write_release_content "dev-0002" >"$scratch/env/release-record.yaml"
git -C "$scratch" add -A
git -C "$scratch" commit -q -m "revision B: dev-0002 supersedes dev-0001 in history"
revision_b=$(git -C "$scratch" rev-parse HEAD)

common_render_args=(--app-repo "$scratch" --env-repo "$scratch"
  --root-app-name dev-root
  --env-repo-url "git@example.invalid:bedoux-commerce-env.git"
  --app-repo-url "git@example.invalid:bedoux-commerce-cloud.git"
  --root-path apps/dev)

### Positive: renders both root and child Applications, each source pinned to an ###
### EXACT commit SHA — never HEAD/a branch. The child is generated by reading the ###
### root's own pointer file, not by the caller naming release-record/values paths ###
### directly (DEF-006). ###
set +e
out1=$("$render" --env-revision "$revision_a" "${common_render_args[@]}" 2>/tmp/apps-pos.err); exit1=$?
set -e
assert "positive: exits 0" "$([[ "$exit1" -eq 0 ]]; echo $?)"
assert "positive: root Application rendered" "$([[ "$out1" == *"name: dev-root"* ]]; echo $?)"
assert "positive: child Application rendered (name came from the root's pointer file, not a CLI flag)" \
  "$([[ "$out1" == *"name: dev-child"* ]]; echo $?)"
assert "positive: root's own source targetRevision is the exact env-revision SHA (revision A), not HEAD/main" \
  "$(printf '%s' "$out1" | awk '/name: dev-root/,/^---/' | grep -q "targetRevision: $revision_a"; echo $?)"
assert "positive: child's env-values source targetRevision is the SAME exact env-revision SHA as root" \
  "$(printf '%s' "$out1" | awk '/name: dev-child/,0' | grep -q "targetRevision: $revision_a"; echo $?)"
assert "positive: child's chart source targetRevision is the release record's own appRevision SHA" \
  "$(printf '%s' "$out1" | grep -q "targetRevision: $pinned_app_sha"; echo $?)"
assert "positive: no targetRevision field's VALUE is HEAD/main/master (explanatory comments may still mention the word 'HEAD' in prose)" \
  "$(printf '%s' "$out1" | grep -E '^\s*targetRevision:' | grep -qE 'targetRevision: (HEAD|main|master)$'; test $? -ne 0; echo $?)"

### DEF-005: the values-only source must carry NO 'path' field (a path there also ###
### makes Argo treat it as manifest-generating, not a pure values reference), and ###
### helm.valueFiles must reference the FULL repo-relative path, not just the ###
### basename (a basename-only $values/values.yaml resolves from the repo root, ###
### not env/values.yaml's actual directory). ###
child_block=$(printf '%s' "$out1" | awk '/name: dev-child/,0')
assert "DEF-005: helm.valueFiles references the full repo-relative values path" \
  "$([[ "$child_block" == *'$values/env/values.yaml'* ]]; echo $?)"
assert "DEF-005: the values-only source (ref: values) has no 'path:' field" \
  "$(printf '%s' "$child_block" | awk '/ref: values/{f=1} f && /path:/{print; exit 1}'; echo $?)"

### MOVING-HEAD NEGATIVE TEST: re-rendering at the SAME, already-pinned revision A ###
### — after the scratch repo's branch has moved on to revision B — must produce ###
### BYTE-IDENTICAL output to the first render. This proves the script never ###
### silently re-resolves to "whatever HEAD is now"; it only ever uses the exact ###
### SHA the caller passed. It also proves the root pointer discovery itself is ###
### revision-scoped, not just the values already read from it. ###
set +e
out2=$("$render" --env-revision "$revision_a" "${common_render_args[@]}" 2>/dev/null); exit2=$?
set -e
assert "moving-HEAD negative test: re-render at the SAME pinned revision A, after the branch moved to B, exits 0" \
  "$([[ "$exit2" -eq 0 ]]; echo $?)"
assert "moving-HEAD negative test: output is byte-identical to the first render at revision A (proves no implicit HEAD tracking)" \
  "$([[ "$out1" == "$out2" ]]; echo $?)"
assert "moving-HEAD negative test: output still names releaseId-A's dev-root/dev-child, never dev-0002's content" \
  "$([[ "$out2" != *"dev-0002"* ]]; echo $?)"

### Rendering EXPLICITLY at the new revision B DOES pick up the new content — ###
### proving the tool is revision-scoped (honors whatever exact SHA it's given), ###
### not simply frozen/broken, and proving "advancing the root" only ever requires ###
### moving --env-revision, never a file self-declaring its own commit SHA. ###
set +e
out3=$("$render" --env-revision "$revision_b" "${common_render_args[@]}" 2>/dev/null); exit3=$?
set -e
assert "explicit render at revision B: exits 0" "$([[ "$exit3" -eq 0 ]]; echo $?)"
assert "explicit render at revision B: differs from revision A's render (the tool is revision-scoped, not stuck)" \
  "$([[ "$out1" != "$out3" ]]; echo $?)"
assert "explicit render at revision B: root's targetRevision is now revision B, not A" \
  "$(printf '%s' "$out3" | awk '/name: dev-root/,/^---/' | grep -q "targetRevision: $revision_b"; echo $?)"

### Negative: passing the literal moving-reference spellings HEAD/main/master must ###
### be refused by name, before touching git at all. ###
for bad_ref in HEAD main master "origin/main" "refs/heads/main"; do
  set +e
  out_bad=$("$render" --env-revision "$bad_ref" "${common_render_args[@]}" 2>&1); exit_bad=$?
  set -e
  assert "moving-reference refused by name: --env-revision '$bad_ref' exits non-zero" "$([[ "$exit_bad" -ne 0 ]]; echo $?)"
  assert "moving-reference refused by name: --env-revision '$bad_ref' error names it a moving reference" \
    "$([[ "$out_bad" == *"moving reference"* ]]; echo $?)"
done

### Negative: nonexistent (well-formed) env-revision commit. ###
set +e
out4=$("$render" --env-revision "0000000000000000000000000000000000000000" "${common_render_args[@]}" 2>&1); exit4=$?
set -e
assert "negative (nonexistent env-revision commit): non-zero exit" "$([[ "$exit4" -ne 0 ]]; echo $?)"
assert "negative (nonexistent env-revision commit): error names it" \
  "$([[ "$out4" == *"does not exist as a commit"* ]]; echo $?)"

### DEF-006: zero child pointer files under --root-path is refused. ###
mkdir -p "$scratch/apps/empty"
git -C "$scratch" add -A && git -C "$scratch" commit -q --allow-empty -m "no-op: apps/empty has no tracked files yet"
set +e
out_zero=$("$render" --env-revision "$revision_a" --app-repo "$scratch" --env-repo "$scratch" \
  --root-app-name dev-root --env-repo-url "git@example.invalid:bedoux-commerce-env.git" \
  --app-repo-url "git@example.invalid:bedoux-commerce-cloud.git" --root-path apps/empty 2>&1); exit_zero=$?
set -e
assert "DEF-006 (zero child pointer files): non-zero exit" "$([[ "$exit_zero" -ne 0 ]]; echo $?)"
assert "DEF-006 (zero child pointer files): error says none found" \
  "$([[ "$out_zero" == *"no child Application pointer file found"* ]]; echo $?)"

### DEF-006: MORE THAN ONE child pointer file under --root-path is refused (no ###
### App-of-Apps fan-out claim yet). ###
cat >"$scratch/apps/dev/dev-child-2.yaml" <<'EOF'
childAppName: dev-child-2
releaseRecordPath: env/release-record.yaml
valuesPath: env/values.yaml
EOF
git -C "$scratch" add -A && git -C "$scratch" commit -q -m "revision C: a second pointer file (fan-out not yet supported)"
revision_c=$(git -C "$scratch" rev-parse HEAD)
set +e
out_multi=$("$render" --env-revision "$revision_c" "${common_render_args[@]}" 2>&1); exit_multi=$?
set -e
assert "DEF-006 (multiple child pointer files): non-zero exit" "$([[ "$exit_multi" -ne 0 ]]; echo $?)"
assert "DEF-006 (multiple child pointer files): error names fan-out as out of scope" \
  "$([[ "$out_multi" == *"App-of-Apps"* ]]; echo $?)"
assert "DEF-006 (multiple child pointer files): revision A (only one pointer there) is unaffected" \
  "$([[ "$out1" == "$out2" ]]; echo $?)"

### Negative: pointer file missing a required field. ###
mkdir -p "$scratch/apps/broken"
cat >"$scratch/apps/broken/pointer.yaml" <<'EOF'
childAppName: broken-child
releaseRecordPath: env/release-record.yaml
EOF
git -C "$scratch" add -A && git -C "$scratch" commit -q -m "revision D: pointer file missing valuesPath"
revision_d=$(git -C "$scratch" rev-parse HEAD)
set +e
out_ptr=$("$render" --env-revision "$revision_d" --app-repo "$scratch" --env-repo "$scratch" \
  --root-app-name dev-root --env-repo-url "git@example.invalid:bedoux-commerce-env.git" \
  --app-repo-url "git@example.invalid:bedoux-commerce-cloud.git" --root-path apps/broken 2>&1); exit_ptr=$?
set -e
assert "negative (pointer file missing valuesPath): non-zero exit" "$([[ "$exit_ptr" -ne 0 ]]; echo $?)"
assert "negative (pointer file missing valuesPath): error names the missing fields" \
  "$([[ "$out_ptr" == *"missing one of: childAppName, releaseRecordPath, valuesPath"* ]]; echo $?)"

### DEF-006 shared validation: reusing render-gitops-release.sh's cross-check ###
### means this script now catches an image digest mismatch it previously ignored ###
### entirely (it used to have no image validation at all). ###
other_digest="sha256:$(python3 -c "import hashlib;print(hashlib.sha256(b'unreviewed-swap').hexdigest())")"
mkdir -p "$scratch/env-alt" "$scratch/apps/mismatch"
cat >"$scratch/env-alt/values-wrong-digest.yaml" <<EOF
pairedAppRevision: "$pinned_app_sha"
api:
  image:
    repository: example.invalid/bedoux-api
    digest: "$other_digest"
web:
  image:
    repository: example.invalid/bedoux-web
    digest: "${web_digest}"
EOF
cat >"$scratch/apps/mismatch/pointer.yaml" <<'EOF'
childAppName: mismatch-child
releaseRecordPath: env/release-record.yaml
valuesPath: env-alt/values-wrong-digest.yaml
EOF
git -C "$scratch" add -A && git -C "$scratch" commit -q -m "revision E: mismatched-digest fixture"
revision_e=$(git -C "$scratch" rev-parse HEAD)
set +e
out_mismatch=$("$render" --env-revision "$revision_e" --app-repo "$scratch" --env-repo "$scratch" \
  --root-app-name dev-root --env-repo-url "git@example.invalid:bedoux-commerce-env.git" \
  --app-repo-url "git@example.invalid:bedoux-commerce-cloud.git" --root-path apps/mismatch 2>&1); exit_mismatch=$?
set -e
assert "DEF-006 shared validation (image digest mismatch, via the root/pointer path): non-zero exit" \
  "$([[ "$exit_mismatch" -ne 0 ]]; echo $?)"
assert "DEF-006 shared validation: error names the digest mismatch, same wording render-gitops-release.sh uses" \
  "$([[ "$out_mismatch" == *"mismatched API image digest"* ]]; echo $?)"

echo
if [[ "$fail_count" -eq 0 ]]; then
  echo "ALL PASS (0 failures)"
  exit 0
else
  echo "$fail_count assertion(s) FAILED"
  exit 1
fi
