{{- if .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.serviceAccount.name }}
  labels:
    {{- include "bedoux.labels" . | nindent 4 }}
{{- end }}
